# Generated by Django 3.2.15 on 2022-10-09 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leilao", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="product_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="products",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid_win_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leilao.products",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
