# Generated by Django 3.2.15 on 2022-10-09 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leilao", "0002_auto_20221009_0145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
